from flask import Flask, render_template, request
import csv
import json

app = Flask(__name__)


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/about")
def about():
    return render_template("about.html")


@app.route("/contact")
def contact():
    return render_template("contact.html")


@app.route("/items")
def items():
    try:
        with open("items.json", "r") as f:
            data = json.load(f)
            items_list = data.get("items")

    except FileNotFoundError:
        items_list = []

    return render_template("items.html", items=items_list)


@app.route("/products")
def products():
    message = ""
    products_to_send = []
    source = request.args.get("source", "")
    if source is None:
        message = "Bad request."

    product_id = request.args.get("id", None)

    if source == "json":
        try:
            with open("products.json", "r") as f:
                products = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            message = "Invalid json file."

    elif source == "csv":
        try:
            with open("products.csv", newline="") as f:
                csv_reader = csv.DictReader(f)
                raw_products = [row for row in csv_reader]

                # Delete whitespace generated by csv
                products = []
                for raw_product in raw_products:
                    product = {k: v.strip() for k, v in raw_product.items()}
                    products.append(product)
        except FileNotFoundError:
            message = "Invalid CSV file."

    else:
        message = "Wrong source"

    if not product_id:
        products_to_send = products

    else:
        # Build the dict in a list by id
        products_to_send = [
            product for product in products if str(product["id"]) == product_id
        ]

    # Error if user specified an id which is not in database
    if not products_to_send:
        message = "Product not found"

    return render_template(
        "product_display.html", products=products_to_send, message=message
    )


if __name__ == "__main__":
    app.run(debug=True, port=5000)
